version: "3.9"

services:
    mongo:
        image: mongo:latest
        ports:
        - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        command: ["mongod", "--quiet", "--logpath", "/dev/null"]
        volumes:
        - mongo_data:/data/db

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: frontend-gdash
        ports:
        - "3000:80"
        depends_on:
            api:
                condition: service_started
        env_file:
        - ./frontend/.env.production

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbit-gdash
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            
        ports:
        - "5672:5672"   # para a conexão do worker/collector
        - "15672:15672" # painel de gerenciamento
    
    api:
        build:
            context: ./api-backend
            dockerfile: Dockerfile
        image: api-gdash
        container_name: api
        environment:
            FRONTEND_URL: ${FRONTEND_URL}
            MODE: ${MODE}
        ports:
        - "3001:3001"
        depends_on:
            mongo:
                condition: service_started
        env_file:
        - ./api-backend/.env
    
    worker:
        build:
            context: ./worker
            dockerfile: Dockerfile
        image: worker-gdash
        env_file:
        - ./worker/.env
        environment:
            RABBITMQ_URL: ${RABBITMQ_URL}
        depends_on:
            rabbitmq:
                condition: service_started
            api:
                condition: service_started
    
    collector:
        build:
            context: ./collector
            dockerfile: Dockerfile
        image: collector-gdash
        env_file:
        - ./collector/.env
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        depends_on:
            rabbitmq:
               condition: service_started 

volumes:
    mongo_data:
